# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Haris Mahmood
email: hello@meetharis.com
description: Designer, developer, instructor and entrepreneur based in Toronto.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.meetharis.com" # the base hostname & protocol for your site
author: Haris Mahmood
collections:
  - works
permalink: /blog/:title/
gems:
  - jekyll-seo-tag
twitter:
  username: harismahmood89
social:
  name: Haris Mahmood
  links:
    - https://twitter.com/harismahmood89
    - https://www.linkedin.com/in/haris-mahmood-1b0b6650
    - https://github.com/harisaurus
# Build settings
markdown: kramdown
